"""What Android asks of a launcher icon: three resources, all of them XML.

`make_icons.py` is the only caller, and the split is `freedesktop.py`'s exactly:
that half and this one know targets and nothing about shapes, `svgpath.py`
knows shapes and nothing about targets. Marks arrive already placed, as the
`(path data, stroke width or None)` pairs a VectorDrawable and an SVG both read,
so nothing here computes geometry -- it only chooses attribute names.

The three resources, and why each exists:

- **`mipmap-anydpi-v26/ic_launcher.xml`** (hand-kept, not written here) is the
  adaptive icon: a background and a foreground the launcher composes and then
  crops to whatever mask it likes. It also names the foreground a third time as
  `monochrome`, which is what Android 13+ recolours for themed icons.
- **`drawable/ic_launcher_foreground.xml`** is that foreground: the mark alone
  on transparency, over a 108-unit viewport of which only a centred 66-unit
  circle is guaranteed to survive cropping.
- **`values/ic_launcher_background.xml`** is the colour behind it. It is a
  separate resource because the adaptive icon takes its background from there
  rather than from the foreground drawable -- so a background colour edit that
  skips it leaves API 26+ showing a new mark on the old colour while every
  other output moves. That is exactly what the previous mark left behind, and
  the reason this file is generated rather than hand-kept.
- **`mipmap/ic_launcher.xml`** is the whole mark, background included, for API
  24-25. Those have no mask and compose nothing, so an icon that does not bring
  its own rounded square does not get one.

Which of the last two a device reads is decided by resource qualifiers alone:
API 26 and up resolve `@mipmap/ic_launcher` to the `mipmap-anydpi-v26` variant,
and API 24-25 fall through to the unqualified one. VectorDrawable is native
from API 21, well under the minSdk 24 this project sets.
"""

VIEWPORT = 108.0  # the adaptive icon's own grid, in which the safe circle is 66


def _vector(size, viewport, body):
    """Wrap `body` in a square <vector> of `size` dp over a `viewport` grid."""
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        # No "--" in the comment: aapt2 rejects it.
        "<!-- Generated by tool/make_icons.py; edit the geometry there. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size:g}dp"\n'
        f'    android:height="{size:g}dp"\n'
        f'    android:viewportWidth="{viewport:g}"\n'
        f'    android:viewportHeight="{viewport:g}">\n'
        f"{body}\n"
        "</vector>\n"
    )


def _paths(marks, fg):
    """Placed marks as <path> elements, real curves kept."""
    elements = []
    for data, stroke in marks:
        if stroke is None:
            elements.append(
                f'    <path\n        android:pathData="{data}"\n        android:fillColor="{fg}" />'
            )
        else:
            elements.append(
                "    <path\n"
                f'        android:pathData="{data}"\n'
                f'        android:strokeColor="{fg}"\n'
                f'        android:strokeWidth="{stroke:.2f}"\n'
                '        android:strokeLineCap="round"\n'
                '        android:strokeLineJoin="round" />'
            )
    return elements


def foreground(marks, fg):
    """The mark alone, on the adaptive icon's 108-unit viewport.

    Also serves as the `monochrome` layer: a flat single-colour mark over
    transparency is exactly the shape a themed icon recolours.
    """
    return _vector(VIEWPORT, VIEWPORT, "\n".join(_paths(marks, fg)))


def legacy(marks, canvas, radius, bg, fg):
    """The whole mark, rounded square included, for the API 24-25 fall-through.

    The 48dp is only the size a launcher asks a legacy icon for; the viewport
    carries the artwork at whatever density it is then rasterised to.
    """
    end = canvas - radius
    background = (
        "    <path\n"
        f'        android:pathData="M{radius:.0f},0 H{end:.0f} '
        f"A{radius:.0f},{radius:.0f} 0 0 1 {canvas:.0f},{radius:.0f} V{end:.0f} "
        f"A{radius:.0f},{radius:.0f} 0 0 1 {end:.0f},{canvas:.0f} H{radius:.0f} "
        f"A{radius:.0f},{radius:.0f} 0 0 1 0,{end:.0f} V{radius:.0f} "
        f'A{radius:.0f},{radius:.0f} 0 0 1 {radius:.0f},0 Z"\n'
        f'        android:fillColor="{bg}" />'
    )
    return _vector(48.0, canvas, "\n".join([background, *_paths(marks, fg)]))


def background_color(bg):
    """The adaptive icon's background colour resource."""
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tool/make_icons.py; edit BG there. -->\n"
        "<resources>\n"
        f'    <color name="ic_launcher_background">{bg}</color>\n'
        "</resources>\n"
    )
