"""What a Linux desktop asks of an application: an icon theme and an entry.

`make_icons.py` is the only caller, and the split is the same one `svgpath.py`
makes at the other end: that half knows shapes and nothing about targets, this
half knows targets and nothing about shapes. The mark, the rasteriser and the
placements stay there; what is here is two freedesktop.org specifications and
nothing else, which is why the renderer arrives as a callable rather than an
import -- the dependency runs one way and there is no cycle to reason about.

The two specs:

- **Icon Theme Specification**. An icon is found by *name* in a theme, not by
  path, so the tree is `share/icons/hicolor/<size>x<size>/apps/<name>.png`
  with `hicolor` the fallback theme every desktop searches last and every
  desktop has. `SIZES` are the theme's own nominal sizes; anything else lands
  in a directory no `index.theme` declares and is simply never found.
  `scalable/apps/<name>.svg` is the same icon with no size at all, which is
  what a HiDPI shell or a large-icon view actually wants.
- **Desktop Entry Specification**. `share/applications/<name>.desktop` is what
  makes the app appear in a launcher, and its `Icon=` is the theme name above.
  `desktop-file-validate` accepts the entry below with no warning; the one
  category is `Development` because a second *main* category is what makes an
  app show up twice in a menu, so `TextEditor` rides alone beside it.

`NAME` is all three at once -- the entry's basename, the icon's name, and the
GTK application id in `linux/CMakeLists.txt` -- and they must not drift.
Wayland has no per-window icon: a compositor identifies a window by the app id
it declares and then looks for `<app id>.desktop`, so on Wayland the entry
being installed *is* the icon. Keeping the three spellings equal is what makes
that work, and `linux/runner/my_application.cc` sets the same string as the
GTK icon name for X11, where a window carries its own.

**No `index.theme` is written.** The bundle's tree is meant to be copied over
`/usr/share`, and a theme index there is the system's file describing every
app's icons, not this one's -- shipping one would overwrite it. The tree is
readable without one precisely because the system's index already declares
these directories.
"""

NAME = "dev.himark.editor"
BINARY = "himark_editor"
SIZES = (16, 24, 32, 48, 64, 128, 256, 512)
NOMINAL = 128  # the size a scalable icon reports when something insists on one

ENTRY = f"""[Desktop Entry]
# Generated by tool/make_icons.py; edit it there.
Type=Application
Version=1.5
Name=Himark Editor
GenericName=Pattern Editor
Comment=Write Himark patterns and test them against a document
Exec={BINARY}
Icon={NAME}
Terminal=false
Categories=Development;TextEditor;
Keywords=himark;pattern;match;search;text;
StartupNotify=true
"""


def svg_document(marks, canvas, radius, bg, fg):
    """The mark on its own rounded square, as one scalable icon.

    `marks` are `(path data, stroke width or None)` pairs already placed on the
    canvas -- the same data an Android VectorDrawable carries, since both read
    SVG path syntax -- so nothing here computes geometry. The rounded square is
    drawn rather than left to the desktop: unlike a launcher mask or iOS, no
    Linux shell imposes a shape, so an icon that does not bring one is a white
    mark on whatever is behind it.
    """
    body = [
        f'  <rect width="{canvas:g}" height="{canvas:g}" '
        f'rx="{radius:g}" ry="{radius:g}" fill="{bg}"/>'
    ]
    for data, stroke in marks:
        if stroke is None:
            body.append(f'  <path d="{data}" fill="{fg}"/>')
        else:
            body.append(
                f'  <path d="{data}" fill="none" stroke="{fg}" '
                f'stroke-width="{stroke:.2f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    joined = "\n".join(body)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Generated by tool/make_icons.py; edit the geometry there. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg"\n'
        f'    width="{NOMINAL}" height="{NOMINAL}" viewBox="0 0 {canvas:g} {canvas:g}">\n'
        f"{joined}\n"
        "</svg>\n"
    )


def write_share(share, svg, raster):
    """Write the whole share/ tree; `raster(size, path)` renders one PNG.

    Returns the number of files written. The layout is deliberately the one a
    package installs into a prefix, so `cp -r share/. /usr/share/` is the whole
    of "installing" this app's desktop integration, and `linux/CMakeLists.txt`
    copies the same tree into the bundle for a build that was never installed.
    """
    entry = share / "applications" / f"{NAME}.desktop"
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_text(ENTRY)
    scalable = share / "icons/hicolor/scalable/apps" / f"{NAME}.svg"
    scalable.parent.mkdir(parents=True, exist_ok=True)
    scalable.write_text(svg)
    for size in SIZES:
        raster(size, share / f"icons/hicolor/{size}x{size}/apps" / f"{NAME}.png")
    return len(SIZES) + 2
